### ISSUE TITLE
I need a response on this project

### ISSUE THREAD

**Issue by fabriguzden** [sumandroid12/SpotifyDownloader#1]
This application, does not work, extracts the music from vkontakte VK, you are fake, saying
This is a simple Android application to download the Spotify song currently on the original client.
Ajjajajajaj I will laugh, not even extract directly from spotify, that is using the vkontakte api to extract the mp3 and making it happen that is spotify
Because the entire internet community is misleading and cheeky

Why not use the api for developers of spotify to extract m4a files currently spotify uses m4a does not use mp3

**Comment by fabriguzden** [comment]
Clarify that it is not necessary to have spotify installed, since you can write the name of the song in the bar that says spotify url and look for the song I want, but extract it from VK https://vk.com/ and not spotify

**Comment by sumandroid12** [comment]
Alright i will add that to the readme(sorry i was being lazy writing it) to clear up any misunderstanding. I did not claim it extracts the stream from spotify all it does is get the track name and artist from spotify client in background and look for the song on an external website.
